// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20250616184712_AddRecursosForzadosTarea")]
    partial class AddRecursosForzadosTarea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AsignacionProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesProyecto", (string)null);
                });

            modelBuilder.Entity("Domain.AsignacionRecursoTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadNecesaria")
                        .HasColumnType("int");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<int>("TareaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("TareaId");

                    b.ToTable("AsignacionesRecursoTarea", (string)null);
                });

            modelBuilder.Entity("Domain.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notificaciones", (string)null);
                });

            modelBuilder.Entity("Domain.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FinEstimado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("Domain.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadDelRecurso")
                        .HasColumnType("int");

                    b.Property<int>("CantidadEnUso")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SePuedeCompartir")
                        .HasColumnType("bit");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Domain.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Duracion")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("EarlyFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EarlyStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EsCritica")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<long>("Holgura")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LateFinish")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LateStart")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<bool>("RecursosForzados")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("Domain.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAdminSistema")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PwdSerializado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasAnnotation("Relational:JsonPropertyName", "Pwd");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("NotificacionUsuario", b =>
                {
                    b.Property<int>("NotificacionesRecibidasId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosNotificadosId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionesRecibidasId", "UsuariosNotificadosId");

                    b.HasIndex("UsuariosNotificadosId");

                    b.ToTable("NotificacionUsuarios", (string)null);
                });

            modelBuilder.Entity("NotificacionUsuario1", b =>
                {
                    b.Property<int>("NotificacionesVistasId")
                        .HasColumnType("int");

                    b.Property<int>("VistaPorUsuariosId")
                        .HasColumnType("int");

                    b.HasKey("NotificacionesVistasId", "VistaPorUsuariosId");

                    b.HasIndex("VistaPorUsuariosId");

                    b.ToTable("NotificacionVistas", (string)null);
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.Property<int>("TareasDependenciaId")
                        .HasColumnType("int");

                    b.Property<int>("TareasSucesorasId")
                        .HasColumnType("int");

                    b.HasKey("TareasDependenciaId", "TareasSucesorasId");

                    b.HasIndex("TareasSucesorasId");

                    b.ToTable("TareaTarea");
                });

            modelBuilder.Entity("TareaUsuario", b =>
                {
                    b.Property<int>("TareasAsignadasId")
                        .HasColumnType("int");

                    b.Property<int>("UsuariosAsignadosId")
                        .HasColumnType("int");

                    b.HasKey("TareasAsignadasId", "UsuariosAsignadosId");

                    b.HasIndex("UsuariosAsignadosId");

                    b.ToTable("UsuarioTarea", (string)null);
                });

            modelBuilder.Entity("Domain.AsignacionProyecto", b =>
                {
                    b.HasOne("Domain.Proyecto", "Proyecto")
                        .WithMany("AsignacionesDelProyecto")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Domain.AsignacionRecursoTarea", b =>
                {
                    b.HasOne("Domain.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recurso");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("Domain.Tarea", b =>
                {
                    b.HasOne("Domain.Proyecto", null)
                        .WithMany("TareasAsociadas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Domain.Estado", "EstadoActual", b1 =>
                        {
                            b1.Property<int>("TareaId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("Fecha")
                                .HasColumnType("datetime2")
                                .HasColumnName("EstadoFecha");

                            b1.Property<int>("Valor")
                                .HasColumnType("int")
                                .HasColumnName("EstadoValor");

                            b1.HasKey("TareaId");

                            b1.ToTable("Tareas");

                            b1.WithOwner()
                                .HasForeignKey("TareaId");
                        });

                    b.Navigation("EstadoActual")
                        .IsRequired();
                });

            modelBuilder.Entity("NotificacionUsuario", b =>
                {
                    b.HasOne("Domain.Notificacion", null)
                        .WithMany()
                        .HasForeignKey("NotificacionesRecibidasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosNotificadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotificacionUsuario1", b =>
                {
                    b.HasOne("Domain.Notificacion", null)
                        .WithMany()
                        .HasForeignKey("NotificacionesVistasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VistaPorUsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaTarea", b =>
                {
                    b.HasOne("Domain.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasDependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasSucesorasId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TareaUsuario", b =>
                {
                    b.HasOne("Domain.Tarea", null)
                        .WithMany()
                        .HasForeignKey("TareasAsignadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosAsignadosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Proyecto", b =>
                {
                    b.Navigation("AsignacionesDelProyecto");

                    b.Navigation("TareasAsociadas");
                });
#pragma warning restore 612, 618
        }
    }
}
